language: node_js
node_js:
- '7.4'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
- TRAVIS=travis CXX=g++-4.8
script:
- npm test
- npm run lint
after_script:
- npm run codecov
notifications:
  email: false
  slack:
    secure: AIsC+M2TqDubRQjZd8T/xJjwdURQh4utHkhvznFvI8icxXXUh+sMjEYou02TyaGcDVeKQRIv2WDouCpgVERZV8m60OT9twfh2GGh8TCmsuNHovxs9SfWJAt29YAjLf9HBCTjTs8lVGePLHK661hUQMcvtVqOaDijmiBwghz/aH1JNqNLVPmk7lGHfUJyQ4dqa16WQ+yKiXGDpCkd7nFd+bG/DKtmE+H8r6xngTadmOBrEuaVLCeNa7A5oXN5aKiKV5/Cuzg+82rTB/O6+3utpVC8Jhhj5QzSxFQafPAM6YRbQbLpSAxUKT5k/st15rdhfrhlZ/wXOWs6vy4WyTqNZwwcml7kXuAK+oKG4ahYUBLsmGFO8BBYM14zfM2ozldZli8iQR/ZBAanEy0sjlBLtBmKp1F+eWkdu7EKzyNkdexkxv1b3A8wx1HkPSwpM/eWslUe3NjPcwboJsqps85rNJ8zXC65Ar5x5KNbIdqlggSEQgGYBkM833Z0G2b1rJG4YFy8aKbNtoGBtbnZR/9XKgCa8wS6/atwwAQ6OdNPqhgcLIJjfU9gg/1mEdtOJ/b0BAIEjhR2vbbblsf0Y6LDGU1YtXFbKLWA57iALljSidAwlStHkKMDxhRJc97sai6uRwYCr3/qnehIGMWshdR8bJfv/cySdDlXvWgadVoi+Lw=
